name: "Deploy and Destroy Hybrid Workflows"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 3'
    - cron: '0 1 * * 3'
    
    - cron: '0 3 * * 4'
    - cron: '0 4 * * 4'
    
    - cron: '0 5 * * 4'
    - cron: '0 6 * * 4'
    
    - cron: '0 13 * * 3'
    - cron: '0 14 * * 3'
    
    - cron: '0 16 * * 3'
    - cron: '0 17 * * 3'
    
    - cron: '0 11 * * 0'
    - cron: '0 13 * * 0'
    
jobs:
  usecase_schedules:
    name: "Trigger Hybrid Usecase Schedules"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # first and fourth use cases are similar so we can skip this if needed
      # Deploy first hybrid use case
      - name: Trigger Deploy workflow1
        run: gh workflow run xc-bigip-apply.yml --ref deploy-xc-bigip
        if: github.event.schedule == '0 11 * * 3'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Destroy first hybrid use case
      - name: Trigger Destroy workflow1
        run: gh workflow run xc-bigip-destroy.yml --ref destroy-xc-bigip
        if: github.event.schedule == '0 4 * * 4'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy second hybrid use case
      - name: Trigger Deploy workflow2
        run: gh workflow run xc-nap-apply.yml --ref deploy-xc-nap
        if: github.event.schedule == '0 3 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Destroy second hybrid use case
      - name: Trigger Destroy workflow2
        run: gh workflow run xc-nap-destroy.yml --ref destroy-xc-nap
        if: github.event.schedule == '0 4 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy third hybrid use case
      - name: Trigger Deploy workflow3
        run: gh workflow run xcapi-nic-apply.yml --ref deploy-xcapi-nic
        if: github.event.schedule == '0 5 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Destroy third hybrid use case
      - name: Trigger Destroy workflow3
        run: gh workflow run xcapi-nic-destroy.yml --ref destroy-xcapi-nic
        if: github.event.schedule == '0 6 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Deploy fourth hybrid use case
      - name: Trigger Deploy workflow4
        run: gh workflow run xc-bigip-apply.yml --ref deploy-xc-bigip
        if: github.event.schedule == '0 13 * * 3'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Destroy fourth hybrid use case
      - name: Trigger Destroy workflow4
        run: gh workflow run xc-bigip-destroy.yml --ref destroy-xc-bigip
        if: github.event.schedule == '0 14 * * 3'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy fifth hybrid use case
      - name: Trigger Deploy workflow5
        run: gh workflow run xcbn-cis-apply.yml --ref deploy-xcbn-cis
        if: github.event.schedule == '0 16 * * 3'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Destroy fifth hybrid use case
      - name: Trigger Destroy workflow5
        run: gh workflow run xcbn-cis-destroy.yml --ref destroy-xcbn-cis
        if: github.event.schedule == '0 17 * * 3'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy GenAI hybrid use case
      - name: Trigger GenAI workflow
        run: gh workflow run hybrid-genai-apply.yml --ref deploy-hybrid-genai
        if: github.event.schedule == '0 11 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Destroy GenAI hybrid use case
      - name: Trigger Destroy GenAI workflow
        run: gh workflow run hybrid-genai-destroy.yml --ref destroy-hybrid-genai
        if: github.event.schedule == '0 13 * * 0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
